compile: linked_list.c
	gcc linked_list.c -o linked_list

run: linked_list
	./linked_list

clean: linked_list
	rm -f linked_list

py: linked_list.py
	python3 linked_list.py

clean_py: linked_list.py
	rm -f linked_list.py
